import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        heading: ["var(--font-family-heading)", "monospace"],
        body: ["var(--font-family-body)", "monospace"],
        mono: ["var(--font-family-mono)", "monospace"],
      },
      colors: {
        primary: {
          DEFAULT: "var(--primary)",
          dim: "var(--primary-dim)",
          muted: "var(--primary-muted)",
        },
        secondary: "#ffd393",
        background: "var(--background)",
        surface: "#131313",
        foreground: "var(--foreground)",
        outline: "#84967e",
        "on-tertiary": "#313030",
        "secondary-container": "#fdaf00",
        "on-secondary-container": "#694600",
        "surface-tint": "#00e639",
        "on-surface-variant": "#b9ccb2",
        error: "#ffb4ab",
        "surface-bright": "#393939",
        "inverse-primary": "#006e16",
        "on-primary-container": "#007117",
        "on-tertiary-container": "#626060",
        "surface-container-highest": "#353535",
        "on-error": "#690005",
        "surface-container-low": "#1b1b1b",
        "on-secondary-fixed": "#281800",
        "surface-container-lowest": "#0e0e0e",
        "tertiary-fixed-dim": "#c9c6c5",
        "on-error-container": "#ffdad6",
        "on-background": "#e2e2e2",
        "primary-fixed": "#72ff70",
        "secondary-fixed-dim": "#ffba43",
        "on-primary-fixed": "#002203",
        "surface-container": "#1f1f1f",
        "secondary-fixed": "#ffddaf",
        "on-primary-fixed-variant": "#00530e",
        "on-secondary": "#432c00",
        "primary-container": "#00ff41",
        "on-primary": "#003907",
        "outline-variant": "#3b4b37",
        "inverse-on-surface": "#303030",
        "on-secondary-fixed-variant": "#614000",
        "on-surface": "#e2e2e2",
        "surface-container-high": "#2a2a2a",
        "error-container": "#93000a",
        "tertiary-fixed": "#e5e2e1",
        "inverse-surface": "#e2e2e2",
        "on-tertiary-fixed": "#1c1b1b",
        "surface-variant": "#353535",
        "tertiary-container": "#dfdcdb",
        "on-tertiary-fixed-variant": "#474646",
        "primary-fixed-dim": "#00e639",
        tertiary: "#fcf8f8",
      },
      spacing: {
        margin: "24px",
        gutter: "16px",
        "container-max": "1440px",
        unit: "4px",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      fontSize: {
        "body-lg": ["18px", { lineHeight: "1.5", letterSpacing: "0em", fontWeight: "400" }],
        "code-sm": ["14px", { lineHeight: "1.4", letterSpacing: "0em", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "1", letterSpacing: "0.1em", fontWeight: "700" }],
        "headline-xl": ["48px", { lineHeight: "1.1", letterSpacing: "-0.05em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "1.3", letterSpacing: "0em", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "1.5", letterSpacing: "0em", fontWeight: "400" }],
      },
      animation: {
        flicker: "flicker 0.1s infinite",
        scan: "scan 8s linear infinite",
        blink: "blink 1s step-end infinite",
      },
      keyframes: {
        flicker: {
          "0%, 19.999%, 22%, 62.999%, 64%, 64.999%, 70%, 100%": { opacity: "1" },
          "20%, 21.999%, 63%, 63.999%, 65%, 69.999%": { opacity: "0.4" },
        },
        scan: {
          "0%": { top: "-100px" },
          "100%": { top: "100vh" },
        },
        blink: {
          "50%": { opacity: "0" },
        },
      },
    },
  },
  plugins: [],
};
export default config;